server:
  port: 8889
  
spring:
  application:
    name: EUREKA-CLIENT-2
    
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/